### ISSUE TITLE
ImportError: cannot import name 'chunk' from 'pychunk' 

### ISSUE THREAD

**Issue by rexdivakar** [bhavaniravi/pychunk#1]
Hey @bhavaniravi the idea seems to be great and i tried the package out but unfortunately I'm not able to test the package via pip installation !!

**Comment by navhits** [comment]
Seems to have been fixed. This is cool btw!
https://github.com/bhavaniravi/pychunk/blob/a99a7d774dc5ece563136aee08f033688892a0ea/pychunk/__init__.py#L1

**Comment by rexdivakar** [comment]
Yes you are correct but the changes are not published, So this fix has to be released to the package else it will break during import!

![image](https://user-images.githubusercontent.com/15235122/197339168-8c6ae85a-3c72-4bc1-b64f-e15f096e6163.png)

**Comment by bhavaniravi** [comment]
Thanks for reporting this. This is fixed now. Can one of you check again and confirm?
